### PR TITLE
Freshen up the project

### PR DESCRIPTION
**Pull request by dizel3d**

### CODE REVIEW

**Comment by dizel3d** [comment]
I signed it!

**Comment by dignifiedquire** [comment]
Thanks, could you check why the tests are failing please?

**Comment by dizel3d** [comment]
Travis-CI uses Linux virtual machines, so we should use Linux-style file paths.
I fixed the problem with cross-platform file paths using node module "path".

**Comment by dignifiedquire** [comment]
Thanks a lot!!

**Comment by dizel3d** [comment]
Thank you too!

**Pull request merged**
